'use client'
import { useRouter } from 'next/navigation'
import Navbar from '@/components/Navbar'

const templates = [
  {
    id: 'interview-prep',
    emoji: '💼',
    title: 'Interview Prep Week',
    desc: 'Crack your next tech interview with focused DSA, system design, and mock sessions.',
    color: '#1e3a5f',
    accent: '#3b82f6',
    tags: ['DSA', 'System Design', 'Mock Interviews'],
    goals: 'Study DSA problems for 3 hours daily focusing on arrays, trees, and graphs. Practice system design for 1 hour daily. Do 1 mock interview every day. Review solutions and patterns for 30 minutes before bed. Take short breaks every 90 minutes.',
    commitments: 'No existing commitments',
    preferences: 'Morning person, peak focus before noon',
  },
  {
    id: 'deep-work',
    emoji: '🎯',
    title: 'Deep Work Week',
    desc: 'Maximum focus on one big project. No distractions, just deep execution.',
    color: '#2e1065',
    accent: '#8b5cf6',
    tags: ['Focus', 'Project', 'Zero Distraction'],
    goals: 'Work on main project for 5 hours daily in deep focus blocks. Review progress for 30 minutes each evening. Plan next day tasks every night. No social media during work hours. Exercise 30 minutes daily to maintain energy.',
    commitments: 'No meetings, no distractions',
    preferences: 'Early morning start at 6am, high energy until 2pm',
  },
  {
    id: 'fitness',
    emoji: '💪',
    title: 'Fitness Week',
    desc: 'Build a strong exercise habit with balanced training and recovery.',
    color: '#052e16',
    accent: '#22c55e',
    tags: ['Gym', 'Cardio', 'Recovery'],
    goals: 'Gym workout for 1.5 hours on Monday Wednesday Friday focusing on strength. Cardio run for 45 minutes on Tuesday and Thursday. Yoga or stretching for 30 minutes daily. Meal prep on Sunday for the week. Sleep 8 hours every night.',
    commitments: 'Work 9am to 6pm weekdays',
    preferences: 'High energy in the morning, prefer workouts before work',
  },
  {
    id: 'student',
    emoji: '📚',
    title: 'Student Week',
    desc: 'Balance college, assignments, studying, and personal time effectively.',
    color: '#3d2000',
    accent: '#f59e0b',
    tags: ['Study', 'Assignments', 'Balance'],
    goals: 'Complete all pending assignments by Wednesday. Study each subject for 1 hour daily. Review lecture notes same day. Group study session on Thursday evening. Prepare for upcoming tests on Friday. Take Sunday completely off.',
    commitments: 'College 9am to 3pm Monday to Friday',
    preferences: 'Productive after college from 4pm to 9pm',
  },
  {
    id: 'launch-week',
    emoji: '🚀',
    title: 'Launch Week',
    desc: 'Ship your product or project. Everything focused on getting it live.',
    color: '#1c1917',
    accent: '#f97316',
    tags: ['Ship', 'Deploy', 'Marketing'],
    goals: 'Finish remaining features for 4 hours daily. Write documentation for 1 hour. Set up deployment and CI/CD pipeline. Write launch post and update README. Record a demo video. Share on LinkedIn and GitHub.',
    commitments: 'Daily standup 10am',
    preferences: 'Night owl, most productive from 8pm to 2am',
  },
  {
    id: 'recovery',
    emoji: '🧘',
    title: 'Recovery Week',
    desc: 'Recharge after a burnout. Light work, self-care, and mental reset.',
    color: '#1e3a5f',
    accent: '#06b6d4',
    tags: ['Rest', 'Self-Care', 'Light Work'],
    goals: 'Light work for 2 hours daily maximum. Meditate for 20 minutes every morning. Walk outside for 45 minutes daily. Read a book for 1 hour before bed. No screens after 9pm. Cook healthy meals at home.',
    commitments: 'Minimal commitments this week',
    preferences: 'No early mornings, gentle pace throughout the day',
  },
  {
    id: 'learning',
    emoji: '🧠',
    title: 'Learn New Tech Week',
    desc: 'Pick up a new framework, language, or tool and build something with it.',
    color: '#052e16',
    accent: '#10b981',
    tags: ['Learning', 'Build', 'Practice'],
    goals: 'Watch tutorials and read docs for 2 hours daily. Build a small project using the new tech for 3 hours daily. Write notes and summaries after each session. Push code to GitHub every day. Share learnings on LinkedIn by Friday.',
    commitments: 'Work 9am to 5pm',
    preferences: 'Morning learner, retain information best before noon',
  },
  {
    id: 'content',
    emoji: '✍️',
    title: 'Content Creation Week',
    desc: 'Write blogs, record videos, and build your personal brand online.',
    color: '#2e1065',
    accent: '#a855f7',
    tags: ['Writing', 'LinkedIn', 'Brand'],
    goals: 'Write one LinkedIn post daily. Write one technical blog post by Thursday. Record a 5 minute YouTube or Loom video about something you built. Engage with 10 posts in your network daily. Update portfolio with latest projects.',
    commitments: 'Regular work hours 9am to 5pm',
    preferences: 'Creative in the evening, write best after 7pm',
  },